# This file was *autogenerated* from the file ./src/main.sage
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1)
import sys
sys.path.insert(_sage_const_1 , '..')

from lib.polyFunctions_core import PolyhedronToHSpaceRep, PolyhedronFromHSpaceRep

def computePoly(A, b):

    P = PolyhedronFromHSpaceRep(A, b, base_ring = QQ)
    
    return P
